using System.Numerics;
using Content.Client._CMU14.Medical.Presentation;
using Content.Client.Message;
using Content.Shared._CMU14.Medical.Human.Data;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client._CMU14.Medical.Human.Diagnostics.Examine;

[GenerateTypedNameReferences]
public sealed partial class CMUInspectInjuriesWindow : DefaultWindow
{
    private const string RememberedSizeKey = "cmu-inspect-injuries";
    private static readonly Vector2 PreferredWindowSize = new(400f, 340f);
    private static readonly Vector2 MinimumWindowSize = new(320f, 240f);

    public CMUInspectInjuriesWindow()
    {
        RobustXamlLoader.Load(this);

        SetSize = CMUMedicalWindowSizing.GetInitialSize(RememberedSizeKey, PreferredWindowSize);
        CMUMedicalWindowSizing.FitToScreen(this, PreferredWindowSize, MinimumWindowSize);
    }

    public void SetReport(string targetName, string markup, BleedSeverity bleeding)
    {
        Title = Loc.GetString("cmu-medical-detailed-examine-window-title", ("target", targetName));
        PatientLabel.Text = targetName;
        BleedingBox.Visible = bleeding != BleedSeverity.None;
        BleedingLabel.Text = Loc.GetString(
            "cmu-medical-detailed-examine-window-bleeding",
            ("tier", DescribeBleeding(bleeding)));
        BleedingLabel.ModulateSelfOverride = BleedingColor(bleeding);
        InjuryText.SetMarkupPermissive(markup);
        InjuryScroll.SetScrollValue(Vector2.Zero);
    }

    private static string DescribeBleeding(BleedSeverity bleeding) => bleeding switch
    {
        BleedSeverity.Trace => "Trace",
        BleedSeverity.Light => "Light",
        BleedSeverity.Moderate => "Moderate",
        BleedSeverity.Heavy => "Heavy",
        BleedSeverity.Critical => "Critical",
        _ => "None",
    };

    private static Color BleedingColor(BleedSeverity bleeding) => bleeding switch
    {
        BleedSeverity.Trace => Color.FromHex("#FFCDC2"),
        BleedSeverity.Light => Color.FromHex("#FFB3B3"),
        BleedSeverity.Moderate => Color.FromHex("#FF8E8E"),
        BleedSeverity.Heavy => Color.FromHex("#FF6868"),
        BleedSeverity.Critical => Color.FromHex("#FF4D4D"),
        _ => Color.FromHex("#B7B0A5"),
    };

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        CMUMedicalWindowSizing.FitToScreen(this, PreferredWindowSize, MinimumWindowSize);
        CMUMedicalWindowSizing.RememberSize(RememberedSizeKey, this);
    }
}
