- type: job
  parent: CMJobBase
  id: CMDoctor
  name: job-cmdoctor-name
  description: job-cmdoctor-desc
  setPreference: false
  playTimeTracker: CMJobDoctor
  requirements:
  - !type:TotalJobsTimeRequirement
    group: CMJobsMedical
    time: 3600 # 1 hour
  ranks:
    RMCRankSecondLT: []
  startingGear: CMGearDoctor
  icon: "CMJobIconDoctor"
  joinNotifyCrew: false
  supervisors: job-cmdoctor-supervisors
  accessGroups:
  - CMMedbay
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillEndurance: 1
        RMCSkillFirearms: 0
        RMCSkillFireman: 1
        RMCSkillMedical: 3
        RMCSkillSurgery: 2
    - type: RMCUserBulkyArmorIncapable
    - type: JobPrefix
      prefix: rmc-job-prefix-doctor
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: doctor
      background:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: background_medical
    - type: MutinyEligible

- type: startingGear
  id: CMGearDoctor
  equipment:
    jumpsuit: CMScrubsBlue
    shoes: ClothingShoesColorWhite
    id: CMIDCardDoctor

- type: startingGear
  id: CMGearDoctorEquipped
  equipment:
    jumpsuit: CMScrubsBlue
    outerClothing: RMCCoatService
    gloves: CMHandsLatex
    shoes: RMCShoesWhite
    head: CMHeadCapSurgBlue
    id: CMIDCardDoctor
    ears: CMHeadsetMedical
    belt: CMBeltMedicalFilled

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointDoctor
  name: ent-CMSpawnPointDoctor
  components:
  - type: SpawnPoint
    job_id: CMDoctor
  - type: Sprite
    state: doc_spawn

- type: entity
  parent: CMGuidebookRole
  id: CMGuidebookRoleDoctor
  name: ent-CMGuidebookRoleDoctor
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    state: doctor

- type: playTimeTracker
  id: CMJobDoctor
  isHumanoid: true
