- type: job
  parent: CMJobBase
  id: AU14JobCivilianMiner
  name: job-au14jobcivilianminer-name
  description: job-au14jobcivilianminer-desc
  setPreference: true
  playTimeTracker: AU14JobCivilianMiner
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCivilianMiner
  icon: "CMJobIconEmpty"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: job-au14jobcivilianminer-supervisors
  spawnMenuRoleName: job-au14jobcivilianminer-spawnmenurolename
  accessGroups:
  - Colonist
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFireman: 2
        RMCSkillVehicles: 2
        RMCSkillDomestics: 1
        RMCSkillFirearms: 2
    - type: JobPrefix
      prefix: au14-job-prefix-civilianminer
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false

- type: startingGear
  id: AU14GearCivilianMiner
  equipment:
    jumpsuit: AU14CivilianKellandMiningClothes
    outerClothing: AU14CivilianHazardVestKellandMiningCorporation
    shoes: RMCBootsCorporate
    id: AU14IDCardColonyColonist

    head: RMCHardhatOrange

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianMiner
  name: ent-AU14SpawnPointCivilianMiner
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianMiner
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianMiner
  isHumanoid: true
