- type: job
  parent: CMJobBase
  id: AU14JobCivilianPrisoner
  name: job-au14jobcivilianprisoner-name
  description: job-au14jobcivilianprisoner-desc
  setPreference: true
  playTimeTracker: AU14JobCivilianPrisoner
  startingGear: AU14GearCivilianPrisoner
  ranks:
    RMCRankCivilian: []
  icon: "AU14JobIconColonyPrisoner"
  hasIcon: false
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: job-au14jobcivilianprisoner-supervisors
  spawnMenuRoleName: job-au14jobcivilianprisoner-spawnmenurolename
  roleWeight: 0.6
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFireman: 1
        RMCSkillVehicles: 1
        RMCSkillDomestics: 1
        RMCSkillFirearms: 2
    - type: JobPrefix
      prefix: au14-job-prefix-civilianprisoner
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false

- type: startingGear
  id: AU14GearCivilianPrisoner
  equipment:
    jumpsuit: AU14CivilianPrisonJumpsuit
    shoes: RMCShoesBlack

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianPrisoner
  name: ent-AU14SpawnPointCivilianPrisoner
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianPrisoner
  - type: Sprite
    state: syn_spawn

- type: entity
  parent: MarkerBase
  id: auprisonerghost
  name: ent-auprisonerghost
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: aughostprisoner

- type: randomHumanoidSettings
  parent: RMCSettingsGhostRole
  id: aughostprisoner
  components:
  - type: RMCJobSpawner
    job: AU14JobCivilianPrisoner

- type: playTimeTracker
  id: AU14JobCivilianPrisoner
  isHumanoid: true
