- type: job
  parent: CMSurvivorEngineer
  id: CMSurvivorCargoTechnician
  name: job-cmsurvivorcargotechnician-name
  description: job-cmsurvivorcargotechnician-desc
  playTimeTracker: CMJobSurvivorEngineer
  startingGear: RMCGearSurvivorCargoTechnician
  spawnMenuRoleName: job-cmsurvivorcargotechnician-spawnmenurolename
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: RMCSkillPresetSurvivorTrucker
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
    - type: EquipEntityPreset
      preset: RMCGearSurvivorPresetCargoTechnician
  useLoadoutOfJob: CMSurvivorEngineer # for inheritance

- type: startingGear
  id: RMCGearSurvivorCargoTechnician
  equipment:
    jumpsuit: RMCJumpsuitCivilianBrown
    back: CMSatchelMarineTechSurvivorFill
    head: RMCHeadBeanieTan
    shoes: RMCShoesJackboots
    gloves: CMHandsBrown
    id: CMIDCardColonistEngineer
    pocket1: RMCPouchSurvivalFill
    pocket2: RMCPouchToolsFill
# TODO RMC Meson Goggles

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorCargoTechnician
  name: ent-RMCSpawnPointSurvivorCargoTechnician
  components:
  - type: SpawnPoint
    job_id: CMSurvivor
  - type: Sprite
    layers:
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv

- type: entity
  parent: RMCSurvivorPresetEngineer
  id: RMCGearSurvivorPresetCargoTechnician
  name: ent-RMCGearSurvivorPresetCargoTechnician
  categories: [ HideSpawnMenu ]
