- type: job
  parent: CMSurvivorICB
  id: CMSurvivorVaraderoICB
  name: job-cmsurvivorvaraderoicb-name
  description: job-cmsurvivorvaraderoicb-desc
  playTimeTracker: CMJobSurvivorCorporate
  spawnMenuRoleName: job-cmsurvivorvaraderoicb-spawnmenurolename
  startingGear: RMCGearSurvivorVaraderoICB
  ranks:
    RMCRankICBCorporateLiaison: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 1
        RMCSkillEndurance: 2
        RMCSkillFireman: 1
        RMCSkillFirearms: 2
    - type: EquipEntityPreset
      preset: RMCSurvivorPresetCorporate
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
    - type: JobPrefix
      prefix: cm-job-prefix-survivor-icb
  useLoadoutOfJob: CMSurvivorCorporate # for inheritance

- type: startingGear
  parent: RMCGearSurvivorICB
  id: RMCGearSurvivorVaraderoICB
  equipment:
    jumpsuit: CMJumpsuitLiaisonBlack
    eyes: RMCSunglasses
  inhand:
  - CMClipboard

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorVaraderoICB
  name: ent-RMCSpawnPointSurvivorVaraderoICB
  components:
  - type: SpawnPoint
    job_id: CMSurvivor
  - type: Sprite
    layers:
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv

- type: entity
  parent: RMCSurvivorPresetCorporate
  id: RMCGearSurvivorPresetICB
  name: ent-RMCGearSurvivorPresetICB
  categories: [ HideSpawnMenu ]
