- type: job
  parent: CMSurvivorScientist
  id: RMCSurvivorNewVaraderoResearcher
  name: job-rmcsurvivornewvaraderoresearcher-name
  description: job-rmcsurvivornewvaraderoresearcher-desc
  playTimeTracker: CMJobSurvivorScientist
  startingGear: RMCGearSurvivorNewVaraderoResearcher
  spawnMenuRoleName: job-rmcsurvivornewvaraderoresearcher-spawnmenurolename
  accessGroups:
  - ColonistMedical
  useLoadoutOfJob: CMSurvivorScientist # for inheritance

- type: startingGear
  parent: RMCGearSurvivorScientist
  id: RMCGearSurvivorNewVaraderoResearcher
  equipment:
    jumpsuit: CMJumpsuitResearch
    outerClothing: RMCLabcoatScience
    shoes: RMCShoesLaceup
    back: RMCSatchelChemistryFill

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorNewVaraderoResearcher
  name: ent-RMCSpawnPointSurvivorNewVaraderoResearcher
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorNewVaraderoResearcher
  - type: Sprite
    layers:
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv
