- type: job
  parent: CMSurvivorEngineer
  id: CMSurvivorTechnician
  name: job-cmsurvivortechnician-name
  description: job-cmsurvivortechnician-desc
  playTimeTracker: CMJobSurvivorEngineer
  startingGear: RMCGearSurvivorTechnician
  spawnMenuRoleName: job-cmsurvivortechnician-spawnmenurolename
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillEndurance: 2
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillEngineer: 2
        RMCSkillConstruction: 2
        RMCSkillPowerLoader: 2
        RMCSkillVehicles: 1
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
    - type: EquipEntityPreset
      preset: RMCGearSurvivorPresetTechnician
  useLoadoutOfJob: CMSurvivorEngineer # for inheritance

- type: startingGear
  parent: RMCGearSurvivorEngineer
  id: RMCGearSurvivorTechnician
  equipment:
    head: RMCHardhatBlue
    jumpsuit: RMCJumpsuitCivilian
    outerClothing: RMCHazardVestBlue

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorTechnician
  name: ent-RMCSpawnPointSurvivorTechnician
  components:
  - type: SpawnPoint
    job_id: CMSurvivor
  - type: Sprite
    layers:
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv

- type: entity
  parent: RMCSurvivorPresetEngineer
  id: RMCGearSurvivorPresetTechnician
  name: ent-RMCGearSurvivorPresetTechnician
  categories: [ HideSpawnMenu ]
