- type: job
  parent: CMJobSquadBase
  id: CMSquadLeader
  name: job-cmsquadleader-name
  description: job-cmsquadleader-desc
  setPreference: false
  playTimeTracker: CMJobSquadLeader
  ranks:
    RMCRankGunnerySergeant: []
    RMCRankStaffSergeant: []
  startingGear: CMGearSquadLeader
  dummyStartingGear: CMGearSquadLeaderEquipped
  icon: "CMJobIconSquadLeader"
  joinNotifyCrew: false
  supervisors: job-cmsquadleader-supervisors
  marineAuthorityLevel: 2
  accessGroups:
  - SquadLeader
  overwatchSortPriority: -6
  #overwatchShowName: true
  #overwatchRoleName: Squad Leader
  roleWeight: 1
  displayWeight: 6
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 2
        RMCSkillCqc: 1
        RMCSkillEndurance: 2
        RMCSkillEngineer: 3
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillIntel: 1
        RMCSkillJtac: 2
        RMCSkillLeadership: 1
        RMCSkillMedical: 1
        RMCSkillVehicles: 1
        RMCSkillPolice: 1
    - type: CMVendorUser
      id: CMSquadLeader
      points: 45
    - type: MarineOrders
      moveOrderSoundMale:
        collection: AU14MaleMoveOrder
      moveOrderSoundFemale:
        collection: AU14FemaleMoveOrder
      focusOrderSoundMale:
        collection: AU14MaleFocusOrder
      focusOrderSoundFemale:
        collection: AU14FemaleFocusOrder
      holdOrderSoundMale:
        collection: AU14MaleHoldOrder
      holdOrderSoundFemale:
        collection: AU14FemaleHoldOrder
    - type: SquadArmorWearer
      leader: true
    - type: SquadLeader
    - type: RMCPointing
    - type: JobPrefix
      prefix: cm-job-prefix-squad-leader
    - type: ViewIntelObjectives
    - type: CommandAccent
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: leader
    - type: RMCTrackable
    - type: MutinyEligible
    - type: RMCAwardRecommendation
    - type: SeeNewPlayers

- type: startingGear
  id: CMGearSquadLeader
  equipment:
    id: CMDogtagSquadLeader

- type: startingGear
  id: CMGearSquadLeaderEquipped
  equipment:
    jumpsuit: JumpsuitMarine
    shoes: CMBootsBlackFilled
    head: CMArmorHelmetM11
    outerClothing: CMArmorB12
    gloves: CMHandsBlackMarine
    id: CMDogtagSquadLeader
    ears: CMHeadsetAlphaLeader

- type: playTimeTracker
  id: CMJobSquadLeader
  isHumanoid: true

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointSquadLeader
  name: ent-CMSpawnPointSquadLeader
  components:
  - type: SpawnPoint
    job_id: CMSquadLeader
  - type: Sprite
    state: leader_spawn

- type: entity
  parent: CMSpawnPointSquadLeader
  id: CMSpawnPointSquadLeaderAlpha
  suffix: ent-CMSpawnPointSquadLeaderAlpha-suffix
  components:
  - type: SquadSpawner
    squad: SquadAlpha
    role: CMSquadLeader
  - type: Sprite
    state: leader_spawn_alpha

- type: entity
  parent: CMSpawnPointSquadLeader
  id: CMSpawnPointSquadLeaderBravo
  suffix: ent-CMSpawnPointSquadLeaderBravo-suffix
  components:
  - type: SquadSpawner
    squad: SquadBravo
    role: CMSquadLeader
  - type: Sprite
    state: leader_spawn_bravo

- type: entity
  parent: CMSpawnPointSquadLeader
  id: CMSpawnPointSquadLeaderCharlie
  suffix: ent-CMSpawnPointSquadLeaderCharlie-suffix
  components:
  - type: SquadSpawner
    squad: SquadCharlie
    role: CMSquadLeader
  - type: Sprite
    state: leader_spawn_charlie

- type: entity
  parent: CMSpawnPointSquadLeader
  id: CMSpawnPointSquadLeaderDelta
  suffix: ent-CMSpawnPointSquadLeaderDelta-suffix
  components:
  - type: SquadSpawner
    squad: SquadDelta
    role: CMSquadLeader
  - type: Sprite
    state: leader_spawn_delta

- type: randomHumanoidSettings
  parent: RMCRandomHumanoidBase
  id: RMCSquadLeader
  components:
  - type: GhostRole
    name: cm-job-name-squad-leader
    description: cm-job-description-squad-leader
    rules: ghost-role-information-nonantagonist-rules
    reregister: false
    raffle:
      settings: default
    job: CMSquadLeader
    requirements:
    - !type:RoleTimeRequirement
      role: CMJobSquadLeader
      time: 1

# Guidebook
- type: entity
  parent: CMGuidebookRole
  id: RMCGuidebookRoleSL
  name: ent-RMCGuidebookRoleSL
  description: ent-RMCGuidebookRoleSL-desc
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    state: squad_leader

- type: entity
  id: RMCGuidebookActionMove
  name: ent-RMCGuidebookActionMove
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    sprite: _RMC14/Actions/marine_actions.rsi
    state: move

- type: entity
  id: RMCGuidebookActionHold
  name: ent-RMCGuidebookActionHold
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    sprite: _RMC14/Actions/marine_actions.rsi
    state: hold

- type: entity
  id: RMCGuidebookActionFocus
  name: ent-RMCGuidebookActionFocus
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    sprite: _RMC14/Actions/marine_actions.rsi
    state: focus
