# combat technician
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaCombatTech
  name: ent-RMCRandomHumanoidDeltaCombatTech
  suffix: ent-RMCRandomHumanoidDeltaCombatTech-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaCombatTech

- type: randomHumanoidSettings
  parent: [RMCCombatTech, RMCDeltaBase]
  id: RMCDeltaCombatTech

# fireteam leader
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaFireteamLeader
  name: ent-RMCRandomHumanoidDeltaFireteamLeader
  suffix: ent-RMCRandomHumanoidDeltaFireteamLeader-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaFireteamLeader

- type: randomHumanoidSettings
  parent: [RMCFireteamLeader, RMCDeltaBase]
  id: RMCDeltaFireteamLeader

# hospital corpsman
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaHospitalCorpsman
  name: ent-RMCRandomHumanoidDeltaHospitalCorpsman
  suffix: ent-RMCRandomHumanoidDeltaHospitalCorpsman-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaHospitalCorpsman

- type: randomHumanoidSettings
  parent: [RMCHospitalCorpsman, RMCDeltaBase]
  id: RMCDeltaHospitalCorpsman

# rifleman
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaRifleman
  name: ent-RMCRandomHumanoidDeltaRifleman
  suffix: ent-RMCRandomHumanoidDeltaRifleman-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaRifleman

- type: randomHumanoidSettings
  parent: [RMCRifleman, RMCDeltaBase]
  id: RMCDeltaRifleman

# smart gun operator
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaSmartGunOperator
  name: ent-RMCRandomHumanoidDeltaSmartGunOperator
  suffix: ent-RMCRandomHumanoidDeltaSmartGunOperator-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaSmartGunOperator

- type: randomHumanoidSettings
  parent: [RMCSmartGunOperator, RMCDeltaBase]
  id: RMCDeltaSmartGunOperator

# squad leader
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaSquadLeader
  name: ent-RMCRandomHumanoidDeltaSquadLeader
  suffix: ent-RMCRandomHumanoidDeltaSquadLeader-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaSquadLeader

- type: randomHumanoidSettings
  parent: [RMCSquadLeader, RMCDeltaBase]
  id: RMCDeltaSquadLeader

# weapons specialist
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaWeaponsSpecialist
  name: ent-RMCRandomHumanoidDeltaWeaponsSpecialist
  suffix: ent-RMCRandomHumanoidDeltaWeaponsSpecialist-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaWeaponsSpecialist

- type: randomHumanoidSettings
  parent: [RMCWeaponsSpecialist, RMCDeltaBase]
  id: RMCDeltaWeaponsSpecialist
