# combat technician
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidEchoCombatTech
  name: ent-RMCRandomHumanoidEchoCombatTech
  suffix: ent-RMCRandomHumanoidEchoCombatTech-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCEchoCombatTech

- type: randomHumanoidSettings
  parent: [RMCCombatTech, RMCEchoBase]
  id: RMCEchoCombatTech

# fireteam leader
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidEchoFireteamLeader
  name: ent-RMCRandomHumanoidEchoFireteamLeader
  suffix: ent-RMCRandomHumanoidEchoFireteamLeader-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCEchoFireteamLeader

- type: randomHumanoidSettings
  parent: [RMCFireteamLeader, RMCEchoBase]
  id: RMCEchoFireteamLeader

# hospital corpsman
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidEchoHospitalCorpsman
  name: ent-RMCRandomHumanoidEchoHospitalCorpsman
  suffix: ent-RMCRandomHumanoidEchoHospitalCorpsman-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCEchoHospitalCorpsman

- type: randomHumanoidSettings
  parent: [RMCHospitalCorpsman, RMCEchoBase]
  id: RMCEchoHospitalCorpsman

# rifleman
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidEchoRifleman
  name: ent-RMCRandomHumanoidEchoRifleman
  suffix: ent-RMCRandomHumanoidEchoRifleman-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCEchoRifleman

- type: randomHumanoidSettings
  parent: [RMCRifleman, RMCEchoBase]
  id: RMCEchoRifleman

# smart gun operator
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidEchoSmartGunOperator
  name: ent-RMCRandomHumanoidEchoSmartGunOperator
  suffix: ent-RMCRandomHumanoidEchoSmartGunOperator-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCEchoSmartGunOperator

- type: randomHumanoidSettings
  parent: [RMCSmartGunOperator, RMCEchoBase]
  id: RMCEchoSmartGunOperator

# squad leader
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidEchoSquadLeader
  name: ent-RMCRandomHumanoidEchoSquadLeader
  suffix: ent-RMCRandomHumanoidEchoSquadLeader-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCEchoSquadLeader

- type: randomHumanoidSettings
  parent: [RMCSquadLeader, RMCEchoBase]
  id: RMCEchoSquadLeader

# weapons specialist
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidEchoWeaponsSpecialist
  name: ent-RMCRandomHumanoidEchoWeaponsSpecialist
  suffix: ent-RMCRandomHumanoidEchoWeaponsSpecialist-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCEchoWeaponsSpecialist

- type: randomHumanoidSettings
  parent: [RMCWeaponsSpecialist, RMCEchoBase]
  id: RMCEchoWeaponsSpecialist
