# combat technician
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidFoxtrotCombatTech
  name: ent-RMCRandomHumanoidFoxtrotCombatTech
  suffix: ent-RMCRandomHumanoidFoxtrotCombatTech-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCFoxtrotCombatTech

- type: randomHumanoidSettings
  parent: [RMCCombatTech, RMCFoxtrotBase]
  id: RMCFoxtrotCombatTech

# fireteam leader
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidFoxtrotFireteamLeader
  name: ent-RMCRandomHumanoidFoxtrotFireteamLeader
  suffix: ent-RMCRandomHumanoidFoxtrotFireteamLeader-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCFoxtrotFireteamLeader

- type: randomHumanoidSettings
  parent: [RMCFireteamLeader, RMCFoxtrotBase]
  id: RMCFoxtrotFireteamLeader

# hospital corpsman
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidFoxtrotHospitalCorpsman
  name: ent-RMCRandomHumanoidFoxtrotHospitalCorpsman
  suffix: ent-RMCRandomHumanoidFoxtrotHospitalCorpsman-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCFoxtrotHospitalCorpsman

- type: randomHumanoidSettings
  parent: [RMCHospitalCorpsman, RMCFoxtrotBase]
  id: RMCFoxtrotHospitalCorpsman

# rifleman
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidFoxtrotRifleman
  name: ent-RMCRandomHumanoidFoxtrotRifleman
  suffix: ent-RMCRandomHumanoidFoxtrotRifleman-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCFoxtrotRifleman

- type: randomHumanoidSettings
  parent: [RMCRifleman, RMCFoxtrotBase]
  id: RMCFoxtrotRifleman

# smart gun operator
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidFoxtrotSmartGunOperator
  name: ent-RMCRandomHumanoidFoxtrotSmartGunOperator
  suffix: ent-RMCRandomHumanoidFoxtrotSmartGunOperator-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCFoxtrotSmartGunOperator

- type: randomHumanoidSettings
  parent: [RMCSmartGunOperator, RMCFoxtrotBase]
  id: RMCFoxtrotSmartGunOperator

# squad leader
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidFoxtrotSquadLeader
  name: ent-RMCRandomHumanoidFoxtrotSquadLeader
  suffix: ent-RMCRandomHumanoidFoxtrotSquadLeader-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCFoxtrotSquadLeader

- type: randomHumanoidSettings
  parent: [RMCSquadLeader, RMCFoxtrotBase]
  id: RMCFoxtrotSquadLeader

# weapons specialist
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidFoxtrotWeaponsSpecialist
  name: ent-RMCRandomHumanoidFoxtrotWeaponsSpecialist
  suffix: ent-RMCRandomHumanoidFoxtrotWeaponsSpecialist-suffix
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCFoxtrotWeaponsSpecialist

- type: randomHumanoidSettings
  parent: [RMCWeaponsSpecialist, RMCFoxtrotBase]
  id: RMCFoxtrotWeaponsSpecialist
  components:
  - type: IgnoreSpecLimits
