
- type: job
  abstract: true
  id: CMJobBase
  isCM: true
  canBeAntag: true
  joinNotifyCrew: false
  medals:
    Bronze: RMCMedalBronzeService
    Silver: RMCMedalSilverService
    Gold: RMCMedalGoldService
    Platinum: RMCMedalPlatinumService
    Ruby: RMCMedalRubyService
    Amethyst: RMCMedalAmethystService
    Emerald: RMCMedalEmeraldService
    Prismatic: RMCMedalPrismaticService

- type: job
  abstract: true
  parent: CMJobBase
  id: CMJobSquadBase
  hasSquad: true

- type: department
  abstract: true
  id: CMDepartmentBase
  isCM: true

# Xeno
- type: job
  abstract: true
  parent: CMJobBase
  id: CMJobXenoBase
  description: job-cmjobxenobase-desc
  joinNotifyCrew: false
  icon: "CMJobIconEmpty"
  supervisors: job-cmjobxenobase-supervisors
  accessGroups:
  - CMAccessXeno
  hasIcon: false
  hidden: true
  isXeno: true

- type: entity
  parent: MarkerBase
  id: CMSpawnPointXeno
  name: ent-CMSpawnPointXeno
  description: ent-CMSpawnPointXeno-desc
  components:
  - type: XenoSpawnPoint
  - type: Sprite
    sprite: _RMC14/Markers/landmarks.rsi
    state: xeno_spawn

- type: entity
  parent: MarkerBase
  id: CMSpawnPointXenoLeader
  name: ent-CMSpawnPointXenoLeader
  description: ent-CMSpawnPointXenoLeader-desc
  components:
  - type: XenoLeaderSpawnPoint
  - type: Sprite
    sprite: _RMC14/Markers/landmarks.rsi
    state: queen_spawn

# Misc
- type: job
  abstract: true
  parent: CMJobBase
  id: RMCJobRibbonBase
  medals:
    Bronze: RMCMedalRibbonBronzeService
    Silver: RMCMedalRibbonWhiteService
    Gold: RMCMedalRibbonYellowService
    Platinum: RMCMedalRibbonBlueService
    Ruby: RMCMedalRibbonRedService
    Emerald: RMCMedalRibbonEmeraldService
    Amethyst: RMCMedalRibbonAmethystService
    Prismatic: RMCMedalRibbonPrismaticService

- type: job
  abstract: true
  parent: CMJobBase
  id: RMCJobNametagBase
  medals:
    Bronze: RMCMedalBronzeNametagService
    Silver: RMCMedalSilverNametagService
    Gold: RMCMedalGoldNametagService
    Platinum: RMCMedalPlatinumNametagService
