- type: job
  parent: CMSurvivorScientist
  id: CMSurvivorTrijentResearcher
  name: job-cmsurvivortrijentresearcher-name
  description: job-cmsurvivortrijentresearcher-desc
  startingGear: RMCGearSurvivorTrijentResearcher
  spawnMenuRoleName: job-cmsurvivortrijentresearcher-spawnmenurolename
  accessGroups:
  - ColonistMedical
  useLoadoutOfJob: CMSurvivorScientist # for inheritance

- type: startingGear
  parent: RMCGearSurvivorScientist
  id: RMCGearSurvivorTrijentResearcher
  equipment:
    head: RMCHeadBeretPurple
    jumpsuit: CMJumpsuitRD
    outerClothing: RMCLabcoatScience
    shoes: RMCShoesLaceupBrown
    back: RMCSatchelChemistryFill

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorTrijentResearcher
  name: ent-RMCSpawnPointSurvivorTrijentResearcher
  components:
  - type: SpawnPoint
    job_id: CMSurvivorTrijentResearcher
  - type: Sprite
    layers:
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv

- type: entity
  parent: RMCSurvivorPresetScientist
  id: RMCSurvivorPresetTrijentResearcher
  name: ent-RMCSurvivorPresetTrijentResearcher # TODO RMC14 random research notes
  categories: [ HideSpawnMenu ]
