- type: job
  parent: RMCSurvivorShivasDoctor
  id: RMCSurvivorShivasPanicRoomDoctor
  name: job-rmcsurvivorshivaspanicroomdoctor-name
  playTimeTracker: CMJobSurvivorDoctor
  startingGear: RMCGearSurvivorShivasDoctor
  spawnMenuRoleName: job-rmcsurvivorshivaspanicroomdoctor-spawnmenurolename
  greeting: rmc-job-greeting-shivas-panic-room-doctor
- type: entity
  parent: RMCSpawnPointSurvivorShivasDoctor
  id: RMCSpawnPointSurvivorShivasPanicRoomDoctor
  name: ent-RMCSpawnPointSurvivorShivasPanicRoomDoctor
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorShivasPanicRoomDoctor
