- type: job
  parent: RMCSurvivorShivasResearcher
  id: RMCSurvivorShivasPanicRoomResearcher
  name: job-rmcsurvivorshivaspanicroomresearcher-name
  playTimeTracker: CMJobSurvivorScientist
  startingGear: RMCGearSurvivorShivasResearcher
  spawnMenuRoleName: job-rmcsurvivorshivaspanicroomresearcher-spawnmenurolename
  greeting: rmc-job-greeting-shivas-panic-room-researcher
- type: entity
  parent: RMCSpawnPointSurvivorShivasResearcher
  id: RMCSpawnPointSurvivorShivasPanicRoomResearcher
  name: ent-RMCSpawnPointSurvivorShivasPanicRoomResearcher
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorShivasPanicRoomResearcher
