- type: job
  parent: CMSurvivor
  id: RMCSurvivorShivasPanicRoomCivilian
  name: job-rmcsurvivorshivaspanicroomcivilian-name
  spawnMenuRoleName: job-rmcsurvivorshivaspanicroomcivilian-spawnmenurolename
  playTimeTracker: CMJobSurvivor

- type: entity
  parent: CMSpawnPointSurvivor
  id: CMSpawnPointPanicRoomSurvivor
  name: ent-CMSpawnPointPanicRoomSurvivor
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorShivasPanicRoomCivilian
