- type: job
  parent: CMSurvivorEngineer
  id: RMCSurvivorShivasEngineer
  name: job-rmcsurvivorshivasengineer-name
  playTimeTracker: CMJobSurvivorEngineer
  startingGear: RMCGearSurvivorShivasEngineer
  spawnMenuRoleName: job-rmcsurvivorshivasengineer-spawnmenurolename
  camouflageStartingGear: null

- type: startingGear
  parent: RMCGearSurvivorEngineer
  id: RMCGearSurvivorShivasEngineer
  equipment:
    head: RMCHeadUshanka
    mask: CMMaskCoif
    outerClothing: RMCCoatSnowSurvivorYellow
    shoes: RMCShoesSnow
    jumpsuit: CMJumpsuitLiaisonBlack

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorShivasEngineer
  name: ent-RMCSpawnPointSurvivorShivasEngineer
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorShivasEngineer
  - type: Sprite
    layers:
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv
