- type: job
  parent: CMSurvivorScientist
  id: RMCSurvivorShivasResearcher
  name: job-rmcsurvivorshivasresearcher-name
  description: job-rmcsurvivorshivasresearcher-desc
  playTimeTracker: CMJobSurvivorScientist
  startingGear: RMCGearSurvivorShivasResearcher
  spawnMenuRoleName: job-rmcsurvivorshivasresearcher-spawnmenurolename
  camouflageStartingGear: null

- type: startingGear
  parent: RMCGearSurvivorScientist
  id: RMCGearSurvivorShivasResearcher
  equipment:
    head: RMCHeadUshanka
    mask: CMMaskCoif
    outerClothing: RMCCoatSnowSurvivorPurple
    gloves: CMHandsLatex
    shoes: RMCShoesSnow
    jumpsuit: CMScrubsBlue

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorShivasResearcher
  name: ent-RMCSpawnPointSurvivorShivasResearcher
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorShivasResearcher
  - type: Sprite
    layers:
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv
