- type: job
  parent: CMJobBase
  id: AU14Jobk9handlerBase
  name: job-au14jobk9handlerbase-name
  description: job-au14jobk9handlerbase-desc
  setPreference: false
  playTimeTracker: AU14JobThirdPartyK9Handler
  basePlaytimeTracker: true
  hidden: true

- type: playTimeTracker
  id: AU14JobThirdPartyK9Handler
  isHumanoid: true
