- type: job
  parent: AU14JobPlatCoBase
  id: AU14JobGOVFORPlatCo
  whitelisted: true
  whitelistParent: RMCWhitelistEasy
  name: job-au14jobgovforplatco-name
  description: job-au14jobgovforplatco-desc
  setPreference: true
  basePlaytimeTracker: true
