- type: job
  parent: CMJobXenoBase
  id: CMXenoLesserDrone
  name: job-cmxenolesserdrone-name
  playTimeTracker: CMJobXenoLesserDrone

- type: playTimeTracker
  id: CMJobXenoLesserDrone
  isXeno: true
