- type: entity
  parent: MarkerBase
  id: RMCSpawnerCorpse
  name: ent-RMCSpawnerCorpse
  suffix: ent-RMCSpawnerCorpse-suffix
  components:
  - type: Sprite
    sprite: _RMC14/Markers/landmarks.rsi
    layers:
    - state: corpse_spawner
  - type: CorpseSpawner
    spawn: RMCCorpse
