- type: job
  parent: CMSurvivorCMBDeputy
  id: CMSurvivorSolarisCMBDeputy
  startingGear: RMCGearSurvivorSolarisCMBDeputy
  spawnMenuRoleName: job-cmsurvivorsolariscmbdeputy-spawnmenurolename

- type: startingGear
  parent: RMCGearSurvivorCMBDeputy
  id: RMCGearSurvivorSolarisCMBDeputy
  equipment:
    shoes: RMCBootsPMC

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorSolarisCMBDeputy
  name: ent-RMCSpawnPointSurvivorSolarisCMBDeputy
  components:
  - type: SpawnPoint
    job_id: CMSurvivorSolarisCMBDeputy
  - type: Sprite
    layers:
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv
