- type: job
  parent: CMSurvivorTrucker
  id: CMSurvivorSolarisTrucker
  name: job-cmsurvivorsolaristrucker-name
  description: job-cmsurvivorsolaristrucker-desc
  startingGear: RMCGearSurvivorSolarisTrucker
  spawnMenuRoleName: job-cmsurvivorsolaristrucker-spawnmenurolename
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: RMCSkillPresetSurvivorTrucker
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
    - type: EquipEntityPreset
      preset: RMCSurvivorPresetTrucker

- type: startingGear
  parent: RMCGearSurvivorTrucker
  id: RMCGearSurvivorSolarisTrucker
  equipment:
    eyes: RMCSunglassesBig
    head: RMCHeadCapTruckerRed
    jumpsuit: CMJumpsuitLiaisonBlack
    # outerClothing: /obj/item/clothing/suit/storage/apron/overalls/red TODO RMC14: port this

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorSolarisTrucker
  name: ent-RMCSpawnPointSurvivorSolarisTrucker
  components:
  - type: SpawnPoint
    job_id: CMSurvivorSolarisTrucker
  - type: Sprite
    layers:
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv
