- type: job # Basically same as NV version, should that one just be moved to multi-map?
  parent: CMSurvivorSecurity
  id: CMSurvivorSolarisILRCPeacekeeper
  name: job-cmsurvivorsolarisilrcpeacekeeper-name
  description: job-cmsurvivorsolarisilrcpeacekeeper-desc
  playTimeTracker: CMJobSurvivorSecurity
  startingGear: RMCGearSurvivorSolarisILRCPeacekeeper
  spawnMenuRoleName: job-cmsurvivorsolarisilrcpeacekeeper-spawnmenurolename
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: RMCSkillPresetSurvivorMarshal
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
    - type: EquipEntityPreset
      preset: RMCGearSurvivorPresetILRCPeacekeeper
  useLoadoutOfJob: CMSurvivorSecurity # for inheritance

- type: startingGear
  parent: RMCGearSurvivorSecurity
  id: RMCGearSurvivorSolarisILRCPeacekeeper
  equipment:
    jumpsuit: RMCJumpsuitRiotControl
    outerClothing: RMCArmorVest
    head: RMCHeadBeretOfficerHos

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorSolarisILRCPeacekeeper
  name: ent-RMCSpawnPointSurvivorSolarisILRCPeacekeeper
  components:
  - type: SpawnPoint
    job_id: CMSurvivorSolarisILRCPeacekeeper
  - type: Sprite
    layers:
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv
