- type: job
  parent: CMJobBase
  id: AU14JobAuxTechBase
  name: job-au14jobauxtechbase-name
  description: job-au14jobauxtechbase-desc
  playTimeTracker: AU14JobGOVFORAuxTech
  basePlaytimeTracker: true
  hidden: true

- type: playTimeTracker
  id: AU14JobGOVFORAuxTech
  isHumanoid: true
