- type: job
  parent: CMJobBase
  id: AU14JobDCCBase
  name: job-au14jobdccbase-name
  description: job-au14jobdccbase-desc
  playTimeTracker: AU14JobGOVFORDCC
  basePlaytimeTracker: true
  hidden: true

- type: playTimeTracker
  id: AU14JobGOVFORDCC
  isHumanoid: true
