- type: job
  parent: CMJobBase
  id: AU14JobMilitaryPoliceBase
  name: job-au14jobmilitarypolicebase-name
  description: job-au14jobmilitarypolicebase-desc
  playTimeTracker: AU14JobGOVFORMilitaryPoliceMan
  basePlaytimeTracker: true
  hidden: true

- type: playTimeTracker
  id: AU14JobGOVFORMilitaryPoliceMan
  isHumanoid: true
