- type: job
  parent: CMJobBase
  id: AU14JobRadioTelephoneOperatorBase
  name: job-au14jobradiotelephoneoperatorbase-name
  description: job-au14jobradiotelephoneoperatorbase-desc
  playTimeTracker: AU14JobGOVFORRadioTelephoneOperator
  basePlaytimeTracker: true
  hidden: true

- type: playTimeTracker
  id: AU14JobGOVFORRadioTelephoneOperator
  isHumanoid: true
