- type: job
  parent: CMSurvivorCorporate
  id: CMSurvivorICB
  name: job-cmsurvivoricb-name
  description: job-cmsurvivoricb-desc
  playTimeTracker: CMJobSurvivorCorporate
  spawnMenuRoleName: job-cmsurvivoricb-spawnmenurolename
  icon: "RMCJobIconICBLiaison"
  ranks:
    RMCRankICBCorporateLiaison: []
  startingGear: RMCGearSurvivorICB
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 1
        RMCSkillEndurance: 2
        RMCSkillFireman: 1
        RMCSkillFirearms: 2
    - type: EquipEntityPreset
      preset: RMCSurvivorPresetCorporate
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
    - type: JobPrefix
      prefix: cm-job-prefix-survivor-icb
  useLoadoutOfJob: CMSurvivorCorporate # for inheritance

- type: startingGear
  parent: RMCGearSurvivorCorporate
  id: RMCGearSurvivorICB
  equipment:
    ears: RMCHeadsetDistressBureauDamaged
    jumpsuit: RMCJumpsuitLiaisonGreyWorkwear
    head: RMCHardhatWhite
    outerClothing: RMCHazardVestBlack
    eyes: RMCGlassesAviators
    gloves: CMHandsInsulated

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorICB
  name: ent-RMCSpawnPointSurvivorICB
  components:
  - type: SpawnPoint
    job_id: CMSurvivor
  - type: Sprite
    layers:
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv
