# gloves
- type: entity
  parent: BaseAction
  id: ActionToggleKnuckleDustersStun
  name: ent-ActionToggleKnuckleDustersStun
  description: ent-ActionToggleKnuckleDustersStun-desc
  components:
  - type: InstantAction
    event: !type:ToggleActionEvent
