- type: job
  parent: CMJobBase
  id: AU14JobCivilianEmergencyResponseOfficer
  name: job-au14jobcivilianemergencyresponseofficer-name
  description: job-au14jobcivilianemergencyresponseofficer-desc
  setPreference: true
  playTimeTracker: AU14JobCivilianEmergencyResponseOfficer
  ranks:
    RMCRankCivilianSeniorOfficer:
    - !type:RoleTimeRequirement
      role: AU14JobCivilianEmergencyResponseOfficer
      time: 72000 # 20 hours
    RMCRankCivilianOfficer: []
  startingGear: AU14GearCivilianEmergencyResponseOfficer
  icon: "AU14JobIconColonyERO"
  hasIcon: false
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: job-au14jobcivilianemergencyresponseofficer-supervisors
  accessGroups:
  - Colonist
  - aumed
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFireman: 3
        RMCSkillVehicles: 2
        RMCSkillDomestics: 1
        RMCSkillEndurance: 2
        RMCSkillMedical: 2
        RMCSkillCqc: 1
        RMCSkillMeleeWeapons: 1
        RMCSkillFirearms: 2
    - type: JobPrefix
      prefix: au14-job-prefix-emergencyresponseofficer
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false

- type: startingGear
  id: AU14GearCivilianEmergencyResponseOfficer
  equipment:
    shoes: RMCBootsPMC

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianEmergencyResponseOfficer
  name: ent-AU14SpawnPointCivilianEmergencyResponseOfficer
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianEmergencyResponseOfficer
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianEmergencyResponseOfficer
  isHumanoid: true
