- type: job
  parent: AUThreatJobBase
  id: AU14JobThreatLeader
  name: au-job-name-threat-leader
  description: au-job-description-threat-leader
  setPreference: true
  playTimeTracker: AUJobThreatLeader
  hidden: false
  supervisors: nobody
  icon: "AU14JobIconThreatLeader"
  jobPreviewEntity: RMCPlayerXenoQueenPreview
  accessGroups:
  - CMAccessXeno
  - CMAccessXenoQueen

- type: playTimeTracker
  id: AUJobThreatLeader

