- type: job
  parent: CMJobXenoBase
  id: AU14JobThreatMember
  name: job-au14jobthreatmember-name
  description: job-au14jobthreatmember-desc
  setPreference: true
  playTimeTracker: AUJobThreatMember
  hidden: false
  supervisors: job-au14jobthreatmember-supervisors
  icon: "AU14JobIconThreatMember"
  jobPreviewEntity: RMCPlayerXenoQueenPreview
  accessGroups:
  - CMAccessXeno
  - CMAccessXenoQueen

- type: playTimeTracker
  id: AUJobThreatMember
