- type: department
  parent: CMDepartmentBase
  id: AU14DepartmentThreat
  name: department-au14departmentthreat-name
  description: department-au14departmentthreat-desc
  color: "#e3ce94"
  roles:
  - AU14JobThreatLeader
  - AU14JobThreatMember
  departmentRadio: null
  headOfDepartment: null

- type: department
  parent: CMDepartmentBase
  id: AU14DepartmentThirdParty
  name: department-au14departmentthirdparty-name
  description: department-au14departmentthirdparty-desc
  color: "#e3ce94"
  roles:
  - AU14JobThirdPartyLeader
  - AU14JobThirdPartyMember
  departmentRadio: null
  headOfDepartment: null

