ent-ClothingRandomSpawner = random colorful costume
    .desc = Generated by neural networks based on the latest fashion trends.
    .suffix = Random visual

ent-ClothingUniformRandom = item
    .desc = Generated by neural networks based on the latest fashion trends.
    .suffix = Random visual

ent-ClothingUniformRandomArmless = colorful hands-free costume
    .desc = Generated by neural networks based on the latest fashion trends.
    .suffix = Random visual

ent-ClothingUniformRandomBra = colorful bra
    .desc = Generated by neural networks based on the latest fashion trends.
    .suffix = Random visual

ent-ClothingUniformRandomShirt = colorful costume
    .desc = Generated by neural networks based on the latest fashion trends.
    .suffix = Random visual

ent-ClothingUniformRandomShorts = colorful pants
    .desc = Generated by neural networks based on the latest fashion trends.
    .suffix = Random visual

ent-ClothingUniformRandomStandard = colorful costume
    .desc = Generated by neural networks based on the latest fashion trends.
    .suffix = Random visual
