# used in NV and LV-624
- type: job
  parent: CMSurvivor
  id: CMSurvivorPriest
  name: job-cmsurvivorpriest-name
  description: job-cmsurvivorpriest-desc
  playTimeTracker: CMJobSurvivor
  startingGear: RMCGearSurvivorPriest
  spawnMenuRoleName: job-cmsurvivorpriest-spawnmenurolename
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 1
        RMCSkillEndurance: 2
        RMCSkillFireman: 2
        RMCSkillFirearms: 2
        RMCSkillLeadership: 1
    - type: EquipEntityPreset
      preset: RMCGearSurvivorPresetPriest
    - type: MarineOrders
      moveOrderSoundMale:
        collection: AU14MaleMoveOrder
      moveOrderSoundFemale:
        collection: AU14FemaleMoveOrder
      focusOrderSoundMale:
        collection: AU14MaleFocusOrder
      focusOrderSoundFemale:
        collection: AU14FemaleFocusOrder
      holdOrderSoundMale:
        collection: AU14MaleHoldOrder
      holdOrderSoundFemale:
        collection: AU14FemaleHoldOrder
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
  useLoadoutOfJob: CMSurvivor # for inheritance

- type: startingGear
  parent: RMCGearSurvivorEquipped
  id: RMCGearSurvivorPriest
  equipment:
    jumpsuit: RMCJumpsuitChaplain
    outerClothing: RMCClothingPriestRobes
    back: CMSatchelFillSurvivorPriest
    shoes: RMCShoesLaceup

- type: entity
  parent: CMSatchelFillSurvivor
  id: CMSatchelFillSurvivorPriest
  suffix: ent-CMSatchelFillSurvivorPriest-suffix
  components:
  - type: StorageFill
    contents:
    - id: RMCBible

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorPriest
  name: ent-RMCSpawnPointSurvivorPriest
  components:
  - type: SpawnPoint
    job_id: CMSurvivor
  - type: Sprite
    layers:
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv

- type: entity
  parent: [RMCSurvivorPresetCivilianRareItem, RMCSurvivorPresetCivilian]
  id: RMCGearSurvivorPresetPriest
  name: ent-RMCGearSurvivorPresetPriest
  categories: [ HideSpawnMenu ]
