- type: entity
  id: CMClosetBombFilled
  parent: CMClosetBomb
  suffix: ent-CMClosetBombFilled-suffix
  components:
  - type: StorageFill
    contents:
##      - id: ClothingHeadHelmetBombSuit
##      - id: ClothingOuterSuitBomb
      - id: CMWirecutter
        prob: 0.9
      - id: CMScrewdriver
        prob: 0.9
      - id: CMMultitool
        prob: 0.5

- type: entity
  id: RMCArmoryLockerBlueFilled
  parent: RMCLockerGunBlue
  suffix: ent-RMCArmoryLockerBlueFilled-suffix
  components:
    - type: StorageFill
      contents:
      - id: RMCWeaponLauncherM81
        amount: 1
      - id: CMArmorRiot
        amount: 3
      - id: ArmorHelmetRiot
        amount: 3
      - id: RMCWeaponShotgunM890Riot
        amount: 3
      - id: RMCBoxShotgunBeanbag
        amount: 3
      - id: CMMaskGas
        amount: 3
      - id: RMCPacketGrenadeFlashBang
        amount: 1

- type: entity
  id: RMCArmoryLockerRedM890Filled
  parent: RMCLockerGunRed
  suffix: ent-RMCArmoryLockerRedM890Filled-suffix
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunM890
      amount: 3
    - id: RMCBoxShellsBuckshot
      amount: 1
    - id: RMCBoxShellsSlugs
      amount: 1

- type: entity
  parent: RMCLockerGunRed
  id: RMCArmoryLockerRedM890FilledSingle
  suffix: ent-RMCArmoryLockerRedM890FilledSingle-suffix
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunM890
      amount: 1
    - id: RMCBoxShellsBuckshot
      amount: 1
    - id: RMCBoxShellsSlugs
      amount: 1

- type: entity
  id: RMCArmoryLockerRedM4SPRFilled
  parent: RMCLockerGunRed
  suffix: ent-RMCArmoryLockerRedM4SPRFilled-suffix
  components:
  - type: StorageFill
    contents:
    - id: WeaponRifleM4SPR
      amount: 4
    - id: RMCBoxMagazineRifleM4SPR
      amount: 1

- type: entity
  id: RMCArmoryLockerRedM63Filled
  parent: RMCLockerGunRed
  suffix: ent-RMCArmoryLockerRedM63Filled-suffix
  components:
  - type: StorageFill
    contents:
    - id: WeaponSMGM63
      amount: 4
    - id: RMCBoxMagazineSMGM63
      amount: 1

- type: entity
  parent: RMCLockerGunRed
  id: RMCArmoryLockerRedM54CMK1AP
  suffix: ent-RMCArmoryLockerRedM54CMK1AP-suffix
  components:
  - type: StorageFill
    contents:
    - id: RMCM54CMK1CaseAP
      amount: 1

- type: entity
  parent: RMCLockerGunRed
  id: RMCArmoryLockerRedM1984
  suffix: ent-RMCArmoryLockerRedM1984-suffix
  components:
  - type: StorageFill
    contents:
    - id: RMCM1984BeltFilled
      amount: 4
    - id: RMCBoxMagazinePistolM1984
      amount: 1
