- type: job
  parent: CMSurvivorDoctor
  id: CMSurvivorFiorinaDoctor
  name: job-cmsurvivorfiorinadoctor-name
  description: job-cmsurvivorfiorinadoctor-desc
  playTimeTracker: CMJobSurvivorDoctor
  startingGear: RMCGearSurvivorFiorinaDoctor
  accessGroups:
  - ColonistMedical
  spawnMenuRoleName: job-cmsurvivorfiorinadoctor-spawnmenurolename
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 1
        RMCSkillEndurance: 2
        RMCSkillFireman: 1
        RMCSkillFirearms: 2
        RMCSkillMedical: 3
        RMCSkillSurgery: 2
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
    - type: EquipEntityPreset
      preset: RMCSurvivorPresetDoctor
  useLoadoutOfJob: CMSurvivorDoctor # for inheritance

- type: startingGear
  parent: RMCGearSurvivorDoctor
  id: RMCGearSurvivorFiorinaDoctor
  equipment:
    jumpsuit: RMCScrubsLightBlue
    head: ArmorHelmetPMC # TODO RMC14: W-Y armored cap resprite?
    ears: RMCHeadsetDistressWeYa

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorFiorinaDoctor
  name: ent-RMCSpawnPointSurvivorFiorinaDoctor
  components:
  - type: SpawnPoint
    job_id: CMSurvivorFiorinaDoctor
  - type: Sprite
    layers:
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv
