- type: job
  parent: CMSurvivorGoon
  id: CMSurvivorLV624CorporateDomeGoon
  name: job-cmsurvivorlv624corporatedomegoon-name
  description: job-cmsurvivorlv624corporatedomegoon-desc
  playTimeTracker: CMJobSurvivor
  spawnMenuRoleName: job-cmsurvivorlv624corporatedomegoon-spawnmenurolename
  icon: "RMCJobIconPMCGoonStandard"
  ranks:
    RMCRankCivilianOfficer: []
  greeting: rmc-job-greeting-corporate-dome-goon
- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorLV624CorporateDomeGoon
  name: ent-RMCSpawnPointSurvivorLV624CorporateDomeGoon
  components:
  - type: SpawnPoint
    job_id: CMSurvivorLV624CorporateDomeGoon
  - type: Sprite # TODO: Replace with landmark sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv_wy

- type: entity
  parent: RMCSurvivorPresetSecurity
  id: RMCGearSurvivorPresetLV624CorporateDomeGoon
  name: ent-RMCGearSurvivorPresetLV624CorporateDomeGoon
