- type: job
  parent: CMSurvivorSecurity
  id: CMSurvivorLV624SecurityGuard
  name: job-cmsurvivorlv624securityguard-name
  startingGear: RMCGearSurvivorLV624SecurityGuard
  hasIcon: true
  icon: RMCJobIconWeYaSec
  spawnMenuRoleName: job-cmsurvivorlv624securityguard-spawnmenurolename
  accessGroups:
  - ColonistSec
  - ColonistCorporate
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: RMCSkillPresetSurvivorMarshal
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - WeYa
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
    - type: EquipEntityPreset
      preset: RMCSurvivorPresetSecurity
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: cmp
      background:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: background_goon

- type: startingGear
  parent: RMCGearSurvivorSecurity
  id: RMCGearSurvivorLV624SecurityGuard
  equipment:
    head: RMCArmorHelmetPMCDark
    jumpsuit: RMCJumsuitWhiteService
    outerClothing: RMCArmorVestWeYa
    ears: RMCHeadsetDistressWeYa
    id: CMIDCardLiaisonColony

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorLV624SecurityGuard
  name: ent-RMCSpawnPointSurvivorLV624SecurityGuard
  components:
  - type: SpawnPoint
    job_id: CMSurvivorLV624SecurityGuard
  - type: Sprite # TODO: Replace with landmark sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - sprite: _RMC14/Markers/cm_jobs.rsi
      state: survivor
