- type: job
  parent: CMSurvivorSecurity
  id: CMSurvivorLV624CorporateDomeGoonEngineer
  name: job-cmsurvivorlv624corporatedomegoonengineer-name
  description: job-cmsurvivorlv624corporatedomegoonengineer-desc
  playTimeTracker: CMJobSurvivorEngineer
  spawnMenuRoleName: job-cmsurvivorlv624corporatedomegoonengineer-spawnmenurolename
  startingGear: RMCGearSurvivorGoon
  icon: "RMCJobIconPMCGoonEngi"
  hasIcon: true
  ranks:
    RMCRankCivilianOfficer: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: RMCSkillPresetSurvivorGoonTechnician
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - WeYa
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: goon_engi
      background:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: background_goon
  greeting: rmc-job-greeting-corporate-dome-goon-engi
- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorLV624CorporateDomeGoonEngineer
  name: ent-RMCSpawnPointSurvivorLV624CorporateDomeGoonEngineer
  components:
  - type: SpawnPoint
    job_id: CMSurvivorLV624CorporateDomeGoonEngineer
  - type: Sprite # TODO: Replace with landmark sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv_wy

- type: entity
  parent: RMCSurvivorPresetSecurity
  id: RMCGearSurvivorPresetLV624CorporateDomeGoonEngineer
  name: ent-RMCGearSurvivorPresetLV624CorporateDomeGoonEngineer

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconPMCGoonEngi
  icon:
    sprite: _RMC14/Interface/cm_job_icons.rsi
    state: weya_goon_engi
