- type: job
  parent: CMSurvivorDoctor
  id: CMSurvivorLV624MedicalTechnician
  name: job-cmsurvivorlv624medicaltechnician-name
  description: job-cmsurvivorlv624medicaltechnician-desc
  startingGear: RMCGearSurvivorLV624MedicalTechnician
  spawnMenuRoleName: job-cmsurvivorlv624medicaltechnician-spawnmenurolename
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 1
        RMCSkillEndurance: 2
        RMCSkillFireman: 1
        RMCSkillFirearms: 2
        RMCSkillMedical: 3
        RMCSkillSurgery: 2
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
    - type: EquipEntityPreset
      preset: RMCGearSurvivorPresetLV624MedicalTechnician
  useLoadoutOfJob: CMSurvivorDoctor # for inheritance

- type: startingGear
  parent: RMCGearSurvivorDoctor
  id: RMCGearSurvivorLV624MedicalTechnician
  equipment:
    head: RMCHeadBlueSoftCap
    jumpsuit: RMCJumpsuitBlueWorkwear
    outerClothing: RMCJacketWindbreakerFirstResponder
    eyes: RMCGlassesMedicalHUDGlasses

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorLV624MedicalTechnician
  name: ent-RMCSpawnPointSurvivorLV624MedicalTechnician
  components:
  - type: SpawnPoint
    job_id: CMSurvivor
  - type: Sprite # TODO: Replace with landmark sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - sprite: _RMC14/Markers/cm_jobs.rsi
      state: survivor

- type: entity
  parent: RMCSurvivorPresetDoctor
  id: RMCGearSurvivorPresetLV624MedicalTechnician
  name: ent-RMCGearSurvivorPresetLV624MedicalTechnician
