- type: job
  parent: AU14JobPlatOpBase
  id: AU14JobGOVFORPlatOpUPP
  requirements: []
  name: Staff Officer
  spawnMenuRoleName: Junior Officer (UPP)
  ranks:
    UPP_Lieutenant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORPlatOp
      time: 216000 # 60 hours
    UPP_JuniorLieutenant: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonJuniorOfficer
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORPlatOpUPP
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: so
    - type: MarineOrders
      moveOrderSoundMale:
        collection: AU14MaleMoveOrder
      moveOrderSoundFemale:
        collection: AU14FemaleMoveOrder
      focusOrderSoundMale:
        collection: AU14MaleFocusOrder
      focusOrderSoundFemale:
        collection: AU14FemaleFocusOrder
      holdOrderSoundMale:
        collection: AU14MaleHoldOrder
      holdOrderSoundFemale:
        collection: AU14FemaleHoldOrder
    - type: UserIFF
      factions:
      - GOVFOR
