- type: job
  parent: AU14JobPlatOpBase
  id: AU14JobGOVFORPlatOpUPP
  name: job-au14jobgovforplatopupp-name
  spawnMenuRoleName: job-au14jobgovforplatopupp-spawnmenurolename
  ranks:
    UPP_Lieutenant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORPlatOp
      time: 216000 # 60 hours
    UPP_JuniorLieutenant: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORPlatOpUPP
