- type: job
  parent: AU14JobSquadSergeantBase
  id: AU14JobGOVFORSquadSergeantWYPMC
  name: job-au14jobgovforsquadsergeantwypmc-name
  ranks:
    AU14RankWeYuEnforcerSenior:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadSergeant
      time: 108000 # 30 hours
    AU14RankWeYuEnforcer: []
  spawnMenuRoleName: job-au14jobgovforsquadsergeantwypmc-spawnmenurolename
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSquadSergeantWYPMC
