- type: job
  parent: AU14JobPlatOpBase
  id: AU14JobGOVFORPlatOpWYPMC
  name: job-au14jobgovforplatopwypmc-name
  description: job-au14jobgovforplatopwypmc-desc
  spawnMenuRoleName: job-au14jobgovforplatopwypmc-spawnmenurolename
  ranks:
    AU14RankWeYuAdjutant: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORPlatOpWYPMC
