- type: job
  parent: AU14JobPlatOpBase
  id: AU14JobGOVFORPlatOpWYPMC
  requirements: []
  name: PMC Operations Adjutant
  description: au14-job-description-govforplatop
  spawnMenuRoleName: Junior Officer (WYPMC)
  ranks:
    AU14RankWeYuAdjutant: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonJuniorOfficer
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORPlatOpWYPMC
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: so
    - type: MarineOrders
      moveOrderSoundMale:
        collection: AU14MaleMoveOrder
      moveOrderSoundFemale:
        collection: AU14FemaleMoveOrder
      focusOrderSoundMale:
        collection: AU14MaleFocusOrder
      focusOrderSoundFemale:
        collection: AU14FemaleFocusOrder
      holdOrderSoundMale:
        collection: AU14MaleHoldOrder
      holdOrderSoundFemale:
        collection: AU14FemaleHoldOrder
    - type: UserIFF
      factions:
      - GOVFOR
