- type: job
  parent: CMSurvivorTrucker
  id: RMCSurvivorKutjevoTrucker
  name: job-rmcsurvivorkutjevotrucker-name
  description: job-rmcsurvivorkutjevotrucker-desc
  startingGear: RMCGearSurvivorKutjevoTrucker
  spawnMenuRoleName: job-rmcsurvivorkutjevotrucker-spawnmenurolename
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFireman: 1
        RMCSkillEngineer: 1
        RMCSkillConstruction: 2
        RMCSkillVehicles: 3
        RMCSkillEndurance: 2
        RMCSkillFirearms: 2
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
    - type: EquipEntityPreset
      preset: RMCGearSurvivorPresetKutjevoTrucker
  useLoadoutOfJob: CMSurvivor # for inheritance

- type: startingGear
  parent: RMCGearSurvivorTrucker
  id: RMCGearSurvivorKutjevoTrucker
  equipment:
    eyes: RMCGogglesKutjevo
    head: ArmorHelmetPMCKutjevo
    mask: RMCMaskKutjevoRespirator
    gloves: CMHandsLightBrown
    jumpsuit: RMCJumpsuitKutjevoJumper

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorKutjevoTrucker
  name: ent-RMCSpawnPointSurvivorKutjevoTrucker
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorKutjevoTrucker
  - type: Sprite
    layers:
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv

- type: entity
  parent: RMCSurvivorPresetTrucker
  id: RMCGearSurvivorPresetKutjevoTrucker
  name: ent-RMCGearSurvivorPresetKutjevoTrucker
  categories: [ HideSpawnMenu ]
