- type: job
  parent: AU14JobPlatCoBase
  id: AU14JobGOVFORPlatCoRMC
  name: au14-job-name-govforplatcoRMC
  description: au14-job-description-govforplatco
  spawnMenuRoleName: Platoon Commander (TWE RMC)
  special:
  - !type:AddComponentSpecial
    components:
    - type: CommendationGiver
    - type: InnateCommandSpeech
    - type: Marine
      Faction: govfor
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: UserIFF
      factions:
      - GOVFOR
    - type: Skills
      preset: AU14SkillPresetPlatoonCommander
    - type: JobPrefix
      prefix: au14-job-prefix-govforplatco
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: co
    - type: MarineOrders
      moveOrderSoundMale:
        collection: AU14MaleMoveOrder
      moveOrderSoundFemale:
        collection: AU14FemaleMoveOrder
      focusOrderSoundMale:
        collection: AU14MaleFocusOrder
      focusOrderSoundFemale:
        collection: AU14FemaleFocusOrder
      holdOrderSoundMale:
        collection: AU14MaleHoldOrder
      holdOrderSoundFemale:
        collection: AU14FemaleHoldOrder
