- type: job
  parent: AU14JobPlatOpBase
  id: AU14JobGOVFORPlatOpRMC
  name: job-au14jobgovforplatoprmc-name
  spawnMenuRoleName: job-au14jobgovforplatoprmc-spawnmenurolename
  ranks:
    RMC_2Lieutenant: []
