- type: job
  parent: AU14JobSquadSergeantBase
  id: AU14JobGOVFORSquadSergeantRMC
  name: job-au14jobgovforsquadsergeantrmc-name
  spawnMenuRoleName: job-au14jobgovforsquadsergeantrmc-spawnmenurolename
  overwatchRoleName: job-au14jobgovforsquadsergeantrmc-overwatchrolename
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-govforsquadsergeantRMC
