- type: job
  parent: CMSurvivor
  id: CMJobSurvivorSoroMiner
  name: job-cmjobsurvivorsorominer-name
  description: job-cmjobsurvivorsorominer-desc
  playTimeTracker: CMJobSurvivor
  startingGear: RMCGearSurvivorSoroMiner
  spawnMenuRoleName: job-cmjobsurvivorsorominer-spawnmenurolename
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: RMCSkillPresetSurvivorMiner
    - type: EquipEntityPreset
      preset: RMCSurvivorPresetCivilian
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - SPP
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage

- type: startingGear
  parent: RMCGearSurvivorBase
  id: RMCGearSurvivorSoroMiner
  equipment:
    head: RMCHardhatWhiteAlt
    jumpsuit: RMCJumpsuitSPPCiv5
    back: CMSatchelEngineer
    outerClothing: RMCOuterClothingExternalWebbingBrown
    shoes: RMCBootsSPP
    pocket2: RMCPouchToolsFill
    gloves: RMCHandsVeteran
  storage:
    back:
    - CMSheetMetal20
    - RMCMaskGasSPP

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorSoroMiner
  name: ent-RMCSpawnPointSurvivorSoroMiner
  components:
  - type: SpawnPoint
    job_id: CMSurvivor
  - type: Sprite
    layers:
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv
