- type: department
  parent: CMDepartmentBase
  id: CMCommand
  name: department-cmcommand-name
  description: department-cmcommand-desc
  color: "#334E6D"
  roles:
  - CMCommandingOfficer
  - CMExecutiveOfficer
  - CMStaffOfficer
  - CMPVEPlatoonCommander
  - CMRoyalMarinesTroopCommanderPVE
  primary: false
  departmentRadio: MarineCommand
  headOfDepartment: CMCommandingOfficer
  hidden: true
