- type: department
  parent: CMDepartmentBase
  id: CMEngineering
  name: department-cmengineering-name
  description: department-cmengineering-desc
  color: "#A66300"
  roles:
  - CMChiefEngineer
  - CMOrdnanceTech
  - CMMaintTech
  departmentRadio: MarineEngineer
  headOfDepartment: CMChiefEngineer
  hidden: true
