- type: department
  parent: CMDepartmentBase
  id: CMMedbay
  name: department-cmmedbay-name
  description: department-cmmedbay-desc
  color: "#008160"
  roles:
  - CMCMO
  - CMDoctor
  - CMResearcher
  - CMNurse
  - RMCFieldDoctor
  departmentRadio: MarineMedical
  headOfDepartment: CMCMO
  hidden: true
