- type: department
  parent: CMDepartmentBase
  id: CMRequisitions
  name: department-cmrequisitions-name
  description: department-cmrequisitions-desc
  color: "#5F4519"
  roles:
  - CMQuartermaster
  - CMCargoTech
  departmentRadio: MarineRequisition
  headOfDepartment: CMQuartermaster
  hidden: true
