- type: department
  parent: CMDepartmentBase
  id: CMAuxiliarySupport
  name: department-cmauxiliarysupport-name
  description: department-cmauxiliarysupport-desc
  color: "#C38312"
  roles:
  - CMAuxiliarySupportOfficer
  - CMPilotDropship
  - CMPilotGunship
  - CMDropshipCrewChief
  - CMIntelOfficer
  - CMSeniorEnlistedAdvisor
  departmentRadio: MarineJTAC
  headOfDepartment: CMAuxiliarySupportOfficer
  hidden: true
