- type: department
  parent: CMDepartmentBase
  id: CMSurvivor
  hidden: true
  name: department-cmsurvivor-name
  description: department-cmsurvivor-desc
  color: "#C38312"
  roles:
  - RMCJobSyntheticColony
  - CMSurvivor
  - CMSurvivorDoctor
  - CMSurvivorEngineer
  - CMSurvivorSecurity
  - CMSurvivorScientist
  - CMSurvivorCorporate
  - RMCSurvivorCommandingOfficer
  - RMCSurvivorMilitary
  departmentRadio: null
  headOfDepartment: null
