- type: job
  parent: AU14Jobk9handlerBase
  id: AU14JobOPFORk9handler
  name: job-au14jobopfork9handler-name
  description: job-au14jobopfork9handler-desc
  setPreference: false
  ranks:
    RMCRankStaffSergeant: []
  startingGear: AU14GearopforPlatoonCorpsman
  icon: "AU14JobIconOPFORK9Handler"
  requireAdminNotify: false
  spawnMenuRoleName: job-au14jobopfork9handler-spawnmenurolename
  joinNotifyCrew: false
  supervisors: job-au14jobopfork9handler-supervisors
  accessGroups:
  - AU14OpforCorpsman
  - AU14OpforSquad
  overwatchSortPriority: -2
  overwatchRoleName: job-au14jobopfork9handler-overwatchrolename
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: Marine
      Faction: opfor
    - type: Skills
      preset: AU14SkillPresetPlatoonHospitalCorpsman
    - type: JobPrefix
      prefix: au14-job-prefix-opfork9handler
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
  hidden: true

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointOPFORK9Handler
  name: ent-AU14SpawnPointOPFORK9Handler
  components:
  - type: SpawnPoint
    job_id: AU14JobOPFORk9handler
  - type: Sprite
    state: syn_spawn

- type: jobIcon
  parent: CMJobIconBase
  id: AU14JobIconOPFORK9Handler
  icon:
    sprite: _AU14/Interface/au14opforjobicons.rsi
    state: k9handler
