- type: entity
  id: BaseMindRole
  name: ent-BaseMindRole
  description: ent-BaseMindRole-desc
  abstract: true
  components:
  - type: MindRole

- type: entity
  parent: BaseMindRole
  id: BaseMindRoleAntag
  abstract: true
  components:
  - type: MindRole
    antag: true
    antagPrototype: GenericAntagonist
    roleType: SoloAntagonist
    sortWeight: 50

#Observer
- type: entity
  parent: BaseMindRole
  id: MindRoleObserver
  name: ent-MindRoleObserver
  components:
  - type: ObserverRole
  - type: MindRole
    sortWeight: -10

#Ghost Roles
- type: entity
  parent: BaseMindRole
  id: MindRoleGhostRoleNeutral
  name: ent-MindRoleGhostRoleNeutral
  components:
  - type: GhostRoleMarkerRole

- type: entity
  parent: MindRoleGhostRoleNeutral
  id: MindRoleGhostRoleFamiliar
  name: ent-MindRoleGhostRoleFamiliar
  components:
  - type: MindRole
    roleType: Familiar

- type: entity
  parent: [ BaseMindRoleAntag, MindRoleGhostRoleNeutral ]
  id: MindRoleGhostRoleFreeAgent
  name: ent-MindRoleGhostRoleFreeAgent
  components:
  - type: MindRole
    roleType: FreeAgent
    antagPrototype: GenericFreeAgent
    sortWeight: 30

- type: entity
  parent: MindRoleGhostRoleNeutral
  id: MindRoleGhostRoleFreeAgentHarmless
  name: ent-MindRoleGhostRoleFreeAgentHarmless
  components:
  - type: MindRole
    roleType: FreeAgent
    sortWeight: 0 # Maybe 10?

- type: entity
  parent: MindRoleGhostRoleNeutral
  id: MindRoleGhostRoleSilicon
  name: ent-MindRoleGhostRoleSilicon
  components:
  - type: MindRole
    roleType: Silicon

- type: entity
  parent: [ BaseMindRoleAntag, MindRoleGhostRoleNeutral ]
  id: MindRoleGhostRoleSiliconAntagonist
  name: ent-MindRoleGhostRoleSiliconAntagonist
  components:
  - type: MindRole
    roleType: SiliconAntagonist
    antagPrototype: GenericSiliconAntagonist
    sortWeight: 30

- type: entity
  parent: [ BaseMindRoleAntag, MindRoleGhostRoleNeutral ]
  id: MindRoleGhostRoleSoloAntagonist
  name: ent-MindRoleGhostRoleSoloAntagonist

- type: entity
  parent: [ BaseMindRoleAntag, MindRoleGhostRoleNeutral ]
  id: MindRoleGhostRoleTeamAntagonist
  name: ent-MindRoleGhostRoleTeamAntagonist
  components:
  - type: MindRole
    roleType: TeamAntagonist
    antagPrototype: GenericTeamAntagonist

# This should be used (or inherited) for team antags that are summoned or converted in large quantities, and are "secondary" to other antags
- type: entity
  parent: MindRoleGhostRoleTeamAntagonist
  id: MindRoleGhostRoleTeamAntagonistFlock
  name: ent-MindRoleGhostRoleTeamAntagonistFlock
  components:
  - type: MindRole
    sortWeight: 40

# The Job MindRole holds the mob's Job prototype
- type: entity
  parent: BaseMindRole
  id: MindRoleJob
  name: ent-MindRoleJob
  # JobPrototype is filled by SharedJobSystem

# Silicon
- type: entity
  parent: BaseMindRole
  id: MindRoleSiliconBrain
  name: ent-MindRoleSiliconBrain
  components:
  - type: MindRole
    roleType: Silicon
  - type: SiliconBrainRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleSubvertedSilicon
  name: ent-MindRoleSubvertedSilicon
  description:
  components:
  - type: MindRole
    antagPrototype: SubvertedSilicon
    roleType: SiliconAntagonist
    subtype: role-subtype-subverted
  - type: SubvertedSiliconRole

# Dragon
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleDragon
  name: ent-MindRoleDragon
  components:
  - type: MindRole
    antagPrototype: Dragon
    roleType: TeamAntagonist
    subtype: role-subtype-dragon
    exclusiveAntag: true
  - type: DragonRole

# Ninja
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleNinja
  name: ent-MindRoleNinja
  components:
  - type: MindRole
    antagPrototype: SpaceNinja
    subtype: role-subtype-ninja
    exclusiveAntag: true
  - type: NinjaRole

# Paradox Clone
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleParadoxClone
  name: ent-MindRoleParadoxClone
  components:
  - type: MindRole
    antagPrototype: ParadoxClone
    subtype: role-subtype-paradox-clone
  - type: ParadoxCloneRole

# Nukies
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleNukeops
  name: ent-MindRoleNukeops
  components:
  - type: MindRole
    roleType: TeamAntagonist
    subtype: role-subtype-nukie
    exclusiveAntag: true
    antagPrototype: Nukeops
  - type: NukeopsRole

- type: entity
  parent: MindRoleNukeops
  id: MindRoleNukeopsMedic
  name: ent-MindRoleNukeopsMedic
  components:
  - type: MindRole
    antagPrototype: NukeopsMedic

- type: entity
  parent: MindRoleNukeops
  id: MindRoleNukeopsCommander
  name: ent-MindRoleNukeopsCommander
  components:
  - type: MindRole
    antagPrototype: NukeopsCommander

# Revolutionaries
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleHeadRevolutionary
  name: ent-MindRoleHeadRevolutionary
  components:
  - type: MindRole
    antagPrototype: HeadRev
    exclusiveAntag: true
    roleType: TeamAntagonist
    subtype: role-subtype-head-revolutionary
  - type: RevolutionaryRole

- type: entity
  parent: MindRoleHeadRevolutionary
  id: MindRoleRevolutionary
  name: ent-MindRoleRevolutionary
  components:
  - type: MindRole
    antagPrototype: Rev
    subtype: role-subtype-revolutionary

# Survivors (Wizard)
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleSurvivor
  name: ent-MindRoleSurvivor
  components:
  - type: MindRole
    antagPrototype: Survivor
    roleType: FreeAgent
    subtype: role-subtype-survivor
  - type: SurvivorRole

# Thief
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleThief
  name: ent-MindRoleThief
  components:
  - type: MindRole
    antagPrototype: Thief
    subtype: role-subtype-thief
  - type: ThiefRole

# Traitors
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleTraitor
  name: ent-MindRoleTraitor
  components:
  - type: MindRole
    antagPrototype: Traitor
    exclusiveAntag: true
    subtype: role-subtype-traitor
  - type: TraitorRole

- type: entity
  parent: MindRoleTraitor
  id: MindRoleTraitorSleeper
  name: ent-MindRoleTraitorSleeper
  components:
  - type: MindRole
    antagPrototype: TraitorSleeper

- type: entity
  parent: MindRoleTraitor
  id: MindRoleTraitorReinforcement
  name: ent-MindRoleTraitorReinforcement
  components:
  - type: MindRole
    roleType: TeamAntagonist
    subtype: role-subtype-traitor-reinforcement
    antagPrototype: GenericTeamAntagonist

# Wizards
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleWizard
  name: ent-MindRoleWizard
  components:
  - type: MindRole
    antagPrototype: Wizard
    exclusiveAntag: true
    subtype: role-subtype-wizard
  - type: WizardRole

# Zombie Squad
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleInitialInfected
  name: ent-MindRoleInitialInfected
  components:
  - type: MindRole
    antagPrototype: InitialInfected
    exclusiveAntag: true
    roleType: TeamAntagonist
    subtype: role-subtype-initial-infected
  - type: InitialInfectedRole

- type: entity
  parent: MindRoleGhostRoleTeamAntagonistFlock
  id: MindRoleZombie
  name: ent-MindRoleZombie
  components:
  - type: MindRole
    antagPrototype: Zombie
    exclusiveAntag: true
    subtype: role-subtype-zombie
  - type: ZombieRole
