- type: job
  parent: AU14JobLEOLeaderBase
  id: AU14JobCivilianCMBMarshal
  name: job-au14jobciviliancmbmarshal-name
  description: job-au14jobciviliancmbmarshal-desc
  setPreference: true
  canBeAntag: false
  ranks:
    AU14RankCMBMarshal: []
  startingGear: AU14GearCivilianCMBMarshal
  icon: "RMCJobIconBureauMarshal"
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: job-au14jobciviliancmbmarshal-supervisors
  spawnMenuRoleName: job-au14jobciviliancmbmarshal-spawnmenurolename
  accessGroups:
  - auadmin
  - aucmb
  - Colonist
  - AUPrisonStaff
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 2
        RMCSkillEndurance: 2
        RMCSkillFirearms: 2
        RMCSkillFireman: 2
        RMCSkillIntel: 1
        RMCSkillMedical: 1
        RMCSkillMeleeWeapons: 1
        RMCSkillOverwatch: 1
        RMCSkillPolice: 2
        RMCSkillLeadership: 1
        RMCSkillVehicles: 1
    - type: JobPrefix
      prefix: au14-job-prefix-cmbmarshal
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false

- type: startingGear
  id: AU14GearCivilianCMBMarshal
  equipment:
    head: RMCHeadCapBureau
    jumpsuit: AU14CMBUniform
    belt: CMBeltSecurityMarshalFilled
    shoes: RMCBootsPMCFilled
    id: AU14IDCardColonyCMBMarshal
    ears: AU14CMBHeadset
    outerClothing: AU14CMBMarshalWindbreaker

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianCMBMarshal
  name: ent-AU14SpawnPointCivilianCMBMarshal
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianCMBMarshal
  - type: Sprite
    state: syn_spawn
- type: entity
  parent: MarkerBase
  id: aumarshallghost
  name: ent-aumarshallghost
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: Aughostmarshall

- type: randomHumanoidSettings
  parent: RMCSettingsGhostRole
  id: Aughostmarshall
  components:
  - type: RMCJobSpawner
    job: AU14JobCivilianCMBMarshal
